### ISSUE TITLE
Connect to ScPerturb

### ISSUE THREAD

**Issue by martingarridorc** [saezlab/networkcommons#13]
Connect with [ScPerturb](https://github.com/sanderlab/scPerturb) datasets

**Comment by deeenes** [comment]
Pull h5ad directly from zenodo

**Comment by saezrodriguez** [comment]
How is the connection done? can one donwload a perturbaiton datset from scperturb-DB adn run network commons 'on the fly'? @deeenes

**Comment by deeenes** [comment]
@saezrodriguez Not yet: The user gets the requested dataset as an `AnnData` object, which is ideal for many downstream methods, including the ones in `networkcommons` and `scverse`:

```
import networkcommons as nc

some_proteomics = nc.data.omics.scperturb('FrangiehIzar2021_protein.h5ad')

some_proteomics
AnnData object with n_obs × n_vars = 218331 × 24
    obs: 'library_preparation_protocol', 'perturbation_2', 'MOI', 'sgRNA', 'UMI_count', 'guide_id', 'umap_x', 'umap_y', 'perturbation', 'tissue_type', 'cancer', 'disease', 'perturbation_type', 'celltype', 'organism', 'perturbation_type_2', 'nperts', 'ngenes', 'ncounts', 'percent_mito', 'percent_ribo'
    var: 'Target', 'Clone', 'TotalSeq A#', 'Barcode', 'Isotype_control', 'ncounts', 'ncells'
```

We choose `AnnData` as the primary format for omics data in `networkcommons`, and we develop each method to operate on this object. Many parts of this plan are not ready yet, what is missing:

- Update the interfaces of already implemented methods to work on `AnnData` and `Network` objects
- Introduce the `Network` object which integrates omics data and networks for all operations that use both or only the latter
