### ISSUE TITLE
Expand method utilities

### ISSUE THREAD

**Issue by vicpaton** [saezlab/networkcommons#42]
Martin's idea https://github.com/saezlab/networkcommons/blob/vignettes_wishlist/3_methods.ipynb

**Comment by smuellerd** [comment]
As discussed with Victor, I wrote a small summary of the methods: https://docs.google.com/document/d/1Lb4ItR4HNRR4FBkiwU_0QkLd7jupt-vk5_Tqls7K1Uk/edit. Maybe this can be a helpful starting point.
